version: 2

updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    reviewers:
      - "dillmantis"
    assignees:
      - "dillmantis"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    
  # Frontend dependencies (if package.json exists in root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    reviewers:
      - "dillmantis"
    assignees:
      - "dillmantis"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    reviewers:
      - "dillmantis"
    assignees:
      - "dillmantis"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci-cd"
      
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    reviewers:
      - "dillmantis"
    assignees:
      - "dillmantis"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
