# Repository settings for Iron Code Studios
# This file configures repository settings via GitHub API

repository:
  name: iron-code-studios
  description: 'Enterprise-grade website for Iron Code Studios - Technology for Social Impact'
  homepage: https://ironcodestudios.org
  topics: 
    - web-development
    - social-impact
    - ngo
    - technology
    - enterprise
    - nodejs
    - html-css-javascript
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  use_squash_pr_title_as_default: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'quality-gate'
          - 'security-scan'
          - 'build'
          - 'integration-tests'
          - 'lighthouse'
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          users: []
          teams: []
      restrictions:
        users: []
        teams: []
        apps: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'quality-gate'
          - 'security-scan'
          - 'build'
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      enforce_admins: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Environment configurations
environments:
  - name: production
    protection_rules:
      - type: required_reviewers
        reviewers:
          - type: User
            id: dillmantis
      - type: wait_timer
        wait_timer: 5
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
      
  - name: staging
    protection_rules:
      - type: required_reviewers
        reviewers:
          - type: User
            id: dillmantis
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      custom_branches:
        - develop
        - staging

# Labels for issue management
labels:
  # Type labels
  - name: bug
    color: 'd73a4a'
    description: Something isn't working
    
  - name: enhancement
    color: 'a2eeef'
    description: New feature or request
    
  - name: documentation
    color: '0075ca'
    description: Improvements or additions to documentation
    
  - name: security
    color: 'd93f0b'
    description: Security-related issues
    
  # Priority labels
  - name: critical
    color: 'b60205'
    description: Critical issues requiring immediate attention
    
  - name: high
    color: 'd93f0b'
    description: High priority issues
    
  - name: medium
    color: 'fbca04'
    description: Medium priority issues
    
  - name: low
    color: '0e8a16'
    description: Low priority issues
    
  # Status labels
  - name: needs-triage
    color: 'ededed'
    description: Requires initial review and categorization
    
  - name: in-progress
    color: '0075ca'
    description: Currently being worked on
    
  - name: blocked
    color: 'e99695'
    description: Blocked by external dependencies
    
  - name: ready-for-review
    color: '0e8a16'
    description: Ready for code review
    
  # Area labels
  - name: frontend
    color: 'c5def5'
    description: Frontend-related changes
    
  - name: backend
    color: 'f9d0c4'
    description: Backend-related changes
    
  - name: ci-cd
    color: 'd4c5f9'
    description: CI/CD pipeline related
    
  - name: dependencies
    color: '0366d6'
    description: Dependency updates
    
  # Social impact labels
  - name: social-impact
    color: '7057ff'
    description: Features that directly support our social mission
    
  - name: accessibility
    color: 'ff6347'
    description: Accessibility improvements
    
  - name: performance
    color: '32cd32'
    description: Performance improvements
