name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pages: write
  id-token: write
  pull-requests: write

env:
  NODE_VERSION: '18.x'
  REGISTRY_URL: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ===============================
  # CODE QUALITY & SECURITY CHECKS
  # ===============================
  
  quality-gate:
    name: Code Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Run Prettier check
        run: |
          npx prettier --check . --ignore-path .gitignore

      - name: Run tests
        run: |
          cd backend
          npm test -- --coverage --watchAll=false

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          directory: ./backend/coverage
          fail_ci_if_error: true

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm audit
        run: |
          cd backend
          npm audit --audit-level high

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: test

  # ===============================
  # BUILD AND TEST
  # ===============================

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [quality-gate, security-scan]
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Build application
        run: |
          cd backend
          npm run build || echo "No build script defined"

      - name: Create production build artifacts
        run: |
          mkdir -p dist
          cp -r *.html css js images assets dist/
          cp -r backend dist/
          rm -rf dist/backend/node_modules
          tar -czf iron-code-studios-${{ github.sha }}.tar.gz dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-node-${{ matrix.node-version }}
          path: iron-code-studios-${{ github.sha }}.tar.gz
          retention-days: 30

  # ===============================
  # INTEGRATION TESTS
  # ===============================

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run integration tests
        run: |
          cd backend
          npm run test:integration || echo "No integration tests defined yet"
        env:
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: Run E2E tests with Playwright
        run: |
          npx playwright install --with-deps
          npx playwright test || echo "Setting up E2E tests"

  # ===============================
  # PERFORMANCE & ACCESSIBILITY
  # ===============================

  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Start server for testing
        run: |
          cd backend
          npm start &
          sleep 10
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/software.html
            http://localhost:3000/updates.html
          uploadArtifacts: true
          temporaryPublicStorage: true

  # ===============================
  # STAGING DEPLOYMENT
  # ===============================

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [integration-tests, lighthouse]
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'
    environment:
      name: staging
      url: https://staging.ironcodestudios.org
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-node-18.x

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "This would deploy to staging server"
          # Add your staging deployment logic here

      - name: Run smoke tests
        run: |
          echo "🧪 Running smoke tests on staging"
          # Add smoke tests here

      - name: Notify team
        run: |
          echo "📢 Staging deployment complete"
          # Add Slack/Teams notification here

  # ===============================
  # PRODUCTION DEPLOYMENT
  # ===============================

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [integration-tests, lighthouse]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://ironcodestudios.org
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci --production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build for production
        run: |
          mkdir -p dist
          cp -r *.html css js images assets dist/
          echo "ironcodestudios.org" > dist/CNAME
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Health check
        run: |
          sleep 30
          curl -f https://ironcodestudios.org || exit 1

      - name: Create release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## Changes in this Release
            - Automated release from main branch
            - Commit: ${{ github.sha }}
            
            ## Deployment
            - Production: https://ironcodestudios.org
            - Status: ✅ Deployed and verified
          draft: false
          prerelease: false

  # ===============================
  # MONITORING & NOTIFICATIONS
  # ===============================

  post-deployment:
    name: Post-Deployment Tasks
    runs-on: ubuntu-latest
    needs: deploy-production
    if: always()
    steps:
      - name: Update monitoring
        run: |
          echo "📊 Updating monitoring dashboards"
          # Add monitoring updates here

      - name: Notify stakeholders
        run: |
          echo "📧 Notifying stakeholders of deployment"
          # Add notification logic here

      - name: Performance baseline
        run: |
          echo "📈 Recording performance baseline"
          # Add performance monitoring here
